### PR TITLE
[E2E Databricks] - fix photon change and ci guidance

### LINKED ISSUE #1112: fix: photon changes and ci guidance
Fix guidance for CI - as pipelines are ingnoring trigger from yml.
Fix code for photon change.
**DoD**
- Add guidance to  Disable implied YAML CI trigger in the ReadMe
- Fix selection of VM serving DB cluster to make sure that merory is >= 4x number of cores

### PR DESCRIPTION
**Pull request by ydaponte**
# Type of PR
- Documentation changes
- Code changes

## Purpose
- Improve guidance on the ci process
- Fix photon changes
- Addressing a couple of bugs in the ReadMe that came up during the Bug Bashes

## Does this introduce a breaking change? If yes, details on what can break
No.

## Author pre-publish checklist
- [ ] Added test to prove my fix is effective or new feature works
- [ X ] No PII in logs
- [ X ] Made corresponding changes to the documentation

## Validation steps
- When deploying the sample, verify that the chosen VM for the Databricks cluster has memory >= 4x number of cores
- On the CI process, verify that when raising a PR we don't have more than 1 trigger firing the ci pipeline (according with the new guidance on the Read Me)

## Issues Closed or Referenced
- Closes #1112

### CODE REVIEW

File: e2e_samples/parking_sensors/scripts/configure_databricks.sh [hunk 1]
```diff
@@ -73,12 +73,14 @@ photon_node_types=$(echo "$node_types" | jq -r '.node_types[] | select(.photon_d
 # Find common VM sizes
 common_vms=$(grep -Fwf <(echo "$photon_node_types") vm_names.txt)
 
-# Find the VM with the least resources
+# Find the least resource option that has at least 4 times the memory compared to the number of cores
```
Comment (bsherwin) [inline e2e_samples/parking_sensors/scripts/configure_databricks.sh:76]: It might be more clear to say "4GB memory for each core" instead of "4 times the memory compared to the number of cores"

**Review by bsherwin — APPROVED** [review]
