### PR TITLE
[Databrics E2E] Feature PR fixes

### LINKED ISSUE #976: feature merge fixes

### PR DESCRIPTION
**Pull request by elenaterenzi**
# Type of PR

- Code changes

## Purpose

- Reduce chattiness of deployment script
- fix small issue in `deploy_azdo_variables.sh`

## Author pre-publish checklist

- [ ] Added test to prove my fix is effective or new feature works
- [x] No PII in logs
- [ ] Made corresponding changes to the documentation

## Issues Closed or Referenced

- Closes #976

### CODE REVIEW

File: e2e_samples/parking_sensors/scripts/deploy_azdo_variables.sh [hunk 1]
```diff
@@ -91,55 +91,57 @@ az pipelines variable-group create \
         databricksNotebookPath="$databricksNotebookPath" \
         databricksClusterId="$databricksClusterId" \
         apiBaseUrl="$apiBaseUrl" \
-    --output json
+     -o none
```
Comment (ydaponte) [inline e2e_samples/parking_sensors/scripts/deploy_azdo_variables.sh:94]: I know you tested it - but I'm just not sure if the indentation here is right? Can you just confirm?

**Review by ydaponte — APPROVED** [review]
I just have a question - otherwise approved! Thanks for catching this!

**Comment by elenaterenzi** [comment]
Yes it works with that indentation. The problem was a missing space before the \

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
